# Generated by Django 2.2.1 on 2019-05-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=5)),
                ('lojacompra', models.IntegerField(choices=[[1, '01-GENIBAU'], [2, '02-PARQUE SÃO JOSE'], [3, '03-JOÃO XXIII'], [4, '04-JARDIM IRACIMA'], [5, '05-SANTOS DUMONT'], [6, '06-MESSEJANA'], [7, '07-PARQUELANDIA'], [8, '08-JOSE BASTOS'], [9, '09-CONCEITO'], [10, '10-BARRA DO CEARA'], [11, '11-EXPEDICIONARIOS'], [12, '12-WASHINGTON SOARES'], [13, '13-CAUCAIA'], [14, '14-BARRA DO CEARA II']])),
                ('sexo', models.CharField(choices=[['F', 'Feminino'], ['M', 'Masculino'], ['N', 'Nenhuma das opções']], max_length=1)),
                ('outeventos', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1)),
                ('alugar', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
