# Generated by Django 2.2.1 on 2019-05-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_auto_20190518_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
