# Generated by Django 2.2.1 on 2019-05-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_auto_20190518_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
