# Generated by Django 2.2.1 on 2019-05-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0006_auto_20190518_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
