# Generated by Django 2.2.1 on 2019-05-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0007_auto_20190518_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
