# Generated by Django 2.2.1 on 2019-05-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0009_auto_20190518_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='lojacompra',
            field=models.IntegerField(choices=[[1, '01-GENIBAU'], [2, '02-PARQUE SÃO JOSE'], [3, '03-JOÃO XXIII'], [4, '04-JARDIM IRACIMA'], [5, '05-SANTOS DUMONT'], [6, '06-MESSEJANA'], [7, '07-PARQUELANDIA'], [8, '08-JOSE BASTOS'], [9, '09-CONCEITO'], [10, '10-BARRA DO CEARA'], [11, '11-EXPEDICIONARIOS'], [12, '12-WASHINGTON SOARES'], [13, '13-CAUCAIA'], [14, '14-BARRA DO CEARA II']]),
        ),
    ]
