# Generated by Django 2.2.1 on 2019-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0010_auto_20190518_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqempresa', models.IntegerField(unique=True)),
                ('nomeempresa', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
